/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    catagory: Catagory;
    menu: Menu;
    testimonal: Testimonal;
    reservation: Reservation;
    'floor-plan': FloorPlan;
    'table-layout': TableLayout;
    'panorama-view': PanoramaView;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    catagory: CatagorySelect<false> | CatagorySelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    testimonal: TestimonalSelect<false> | TestimonalSelect<true>;
    reservation: ReservationSelect<false> | ReservationSelect<true>;
    'floor-plan': FloorPlanSelect<false> | FloorPlanSelect<true>;
    'table-layout': TableLayoutSelect<false> | TableLayoutSelect<true>;
    'panorama-view': PanoramaViewSelect<false> | PanoramaViewSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catagory".
 */
export interface Catagory {
  id: number;
  name: string;
  description?: string | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  title: string;
  description?: string | null;
  date: string;
  catagory: number | Catagory;
  price: number;
  oldPrice?: number | null;
  volume?: string | null;
  label?: string | null;
  kcal?: number | null;
  image: number | Media;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonal".
 */
export interface Testimonal {
  id: number;
  /**
   * TikTok or Instagram post/reel URL
   */
  videoUrl: string;
  /**
   * Fallback thumbnail shown before embed loads
   */
  coverImage?: (number | null) | Media;
  handle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservation".
 */
export interface Reservation {
  id: number;
  customer: {
    name: string;
    phone: string;
    email?: string | null;
  };
  /**
   * Date and start time of the reservation
   */
  reservationDate: string;
  /**
   * Expected duration in minutes (default: 90)
   */
  duration?: number | null;
  /**
   * The specific chairs reserved for this booking
   */
  bookedChairs?:
    | {
        /**
         * The table this chair belongs to
         */
        table: number | TableLayout;
        /**
         * The chair ID within the table (e.g. C1, C2)
         */
        chairId: string;
        id?: string | null;
      }[]
    | null;
  status?: ('pending' | 'confirmed' | 'cancelled') | null;
  /**
   * Internal notes for staff
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "table-layout".
 */
export interface TableLayout {
  id: number;
  /**
   * Auto-generated if left blank
   */
  tableNumber?: string | null;
  /**
   * Which floor plan this table belongs to
   */
  floor?: (number | null) | FloorPlan;
  type: 'square' | 'round' | 'rectangle';
  zone?: ('window' | 'main-floor' | 'bar-area' | 'patio' | 'private') | null;
  /**
   * Maximum number of seats at this table
   */
  capacity?: number | null;
  position: {
    x: number;
    y: number;
    rotation?: number | null;
  };
  width?: number | null;
  height?: number | null;
  isActive?: boolean | null;
  /**
   * Each chair is a seat at this table. IDs are auto-assigned (C1, C2, …).
   */
  chairs?:
    | {
        /**
         * Unique chair ID within this table (e.g. C1). Auto-assigned.
         */
        chairId?: string | null;
        /**
         * Optional display label (e.g. Window Seat)
         */
        seatLabel?: string | null;
        relativePosition?: {
          x?: number | null;
          y?: number | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "floor-plan".
 */
export interface FloorPlan {
  id: number;
  name: string;
  backgroundImage?: (number | null) | Media;
  canvasWidth?: number | null;
  canvasHeight?: number | null;
  theme?: {
    /**
     * Hex or CSS color for table fill
     */
    tableFillColor?: string | null;
    /**
     * Hex or CSS color for available chairs
     */
    chairFillColor?: string | null;
    /**
     * Hex or CSS color for text labels
     */
    textFillColor?: string | null;
    /**
     * Hex or CSS color for selected items
     */
    selectionColor?: string | null;
    /**
     * Hex or CSS color for booked/unavailable chairs
     */
    bookedColor?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "panorama-view".
 */
export interface PanoramaView {
  id: number;
  /**
   * e.g. "Main Restaurant Tour"
   */
  name: string;
  /**
   * Optional — link to the matching 2D floor plan
   */
  linkedFloorPlan?: (number | null) | FloorPlan;
  /**
   * Each scene is one 360° panorama photo. Add one per zone/area.
   */
  scenes?:
    | {
        /**
         * URL-safe slug, e.g. "main-floor", "patio". Auto-set by editor.
         */
        sceneId: string;
        /**
         * Display name shown on the scene tab, e.g. "Main Floor"
         */
        label: string;
        /**
         * Equirectangular 360° photo (JPG/PNG, ideally 4096×2048px)
         */
        panoramaImage?: (number | null) | Media;
        /**
         * Initial horizontal camera angle when scene loads (-180 → 180)
         */
        defaultYaw?: number | null;
        /**
         * Initial vertical camera angle when scene loads (-90 → 90)
         */
        defaultPitch?: number | null;
        hotspots?:
          | {
              key?: string | null;
              type?: ('table' | 'navigate') | null;
              yaw?: number | null;
              pitch?: number | null;
              table?: (number | null) | TableLayout;
              tableNumber?: string | null;
              targetSceneId?: string | null;
              targetSceneLabel?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'catagory';
        value: number | Catagory;
      } | null)
    | ({
        relationTo: 'menu';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'testimonal';
        value: number | Testimonal;
      } | null)
    | ({
        relationTo: 'reservation';
        value: number | Reservation;
      } | null)
    | ({
        relationTo: 'floor-plan';
        value: number | FloorPlan;
      } | null)
    | ({
        relationTo: 'table-layout';
        value: number | TableLayout;
      } | null)
    | ({
        relationTo: 'panorama-view';
        value: number | PanoramaView;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catagory_select".
 */
export interface CatagorySelect<T extends boolean = true> {
  name?: T;
  description?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  date?: T;
  catagory?: T;
  price?: T;
  oldPrice?: T;
  volume?: T;
  label?: T;
  kcal?: T;
  image?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonal_select".
 */
export interface TestimonalSelect<T extends boolean = true> {
  videoUrl?: T;
  coverImage?: T;
  handle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservation_select".
 */
export interface ReservationSelect<T extends boolean = true> {
  customer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  reservationDate?: T;
  duration?: T;
  bookedChairs?:
    | T
    | {
        table?: T;
        chairId?: T;
        id?: T;
      };
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "floor-plan_select".
 */
export interface FloorPlanSelect<T extends boolean = true> {
  name?: T;
  backgroundImage?: T;
  canvasWidth?: T;
  canvasHeight?: T;
  theme?:
    | T
    | {
        tableFillColor?: T;
        chairFillColor?: T;
        textFillColor?: T;
        selectionColor?: T;
        bookedColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "table-layout_select".
 */
export interface TableLayoutSelect<T extends boolean = true> {
  tableNumber?: T;
  floor?: T;
  type?: T;
  zone?: T;
  capacity?: T;
  position?:
    | T
    | {
        x?: T;
        y?: T;
        rotation?: T;
      };
  width?: T;
  height?: T;
  isActive?: T;
  chairs?:
    | T
    | {
        chairId?: T;
        seatLabel?: T;
        relativePosition?:
          | T
          | {
              x?: T;
              y?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "panorama-view_select".
 */
export interface PanoramaViewSelect<T extends boolean = true> {
  name?: T;
  linkedFloorPlan?: T;
  scenes?:
    | T
    | {
        sceneId?: T;
        label?: T;
        panoramaImage?: T;
        defaultYaw?: T;
        defaultPitch?: T;
        hotspots?:
          | T
          | {
              key?: T;
              type?: T;
              yaw?: T;
              pitch?: T;
              table?: T;
              tableNumber?: T;
              targetSceneId?: T;
              targetSceneLabel?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}